version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: acct_user
      POSTGRES_PASSWORD: acct_pass
      POSTGRES_DB: accounting
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ../backend
    env_file: ../backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg://acct_user:acct_pass@db:5432/accounting
      SECRET_KEY: change_me
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
volumes:
  db_data:
